# Generated by Django 3.2.4 on 2022-12-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='')),
            ],
        ),
    ]
